### ISSUE TITLE
how to enable the fetch robot with a navigation system

### ISSUE THREAD

**Issue by zhouliang-yu** [mcarfagno/gym-panda-reach#1]
Hi @mcarfagno, thx for your amazing code about the fetch robot.
I wonder if, in your environment, the fetch robot can move from one spot to another with a navigation system.

**Comment by mcarfagno** [comment]
Hello, the simulation has only a fixed-base arm, see:
```
 self.pandaUid = p.loadURDF(
            os.path.join(urdfRootPath, "franka_panda/panda.urdf"),
            basePosition=[0, 0, 0.65],
            useFixedBase=True,
        )
```

generally speaking ,if you have a non-fixed base robot, you can achieve navigation very easily in pybullet:
- odometry
```
import pybullet as p
def odometry(robotId):
    """returns [position_x, position_y, forward_velocity, heading_angle] """
    robPos, robOrn = p.getBasePositionAndOrientation(robotId)
    linVel, angVel = p.getBaseVelocity(robotId)

    return np.array(
        [
            robPos[0],
            robPos[1],
            np.sqrt(linVel[0] ** 2 + linVel[1] ** 2),
            p.getEulerFromQuaternion(robOrn)[2],
        ]
    )
```
- base movement:
```
def apply_velocity(robotId, vel_forward, vel_rot)
    p.resetBaseVelocity(robotId, [vel_forward, 0, 0], [0, 0, vel_rot])
```
this is a very simple example, usually you would have a wheel joint motors to which require torque (see [here](https://github.com/StanfordVL/iGibson/blob/master/igibson/controllers/dd_controller.py))
